const products = [
  {
    id: 1,
    title: "Grafikdesign",
    img: "/productsImage/design.webp",
    description: "Logo Design, Corporate Design, Geschäftsausstattung",
    path: "/grafikdesign",
    detailImages: ["/productDetailImage/grafikdesign.webp"],
    detailDescription: [
      "Logo Design",
      "Corporate Design",
      "Printdesign",
      "Layout-Gestaltung",
      "Verpackungdesign",
      "Werbemittelgestaltung",
      "Illustrationen",
      "Vektorisierung",
      "Maskotchendesign",
    ],
  },
  {
    id: 2,
    title: "Printmedien",
    img: "/productsImage/print.webp",
    description: "Flyer, Visitenkarten, Briefpapier",
    path: "/printmedien",
    detailImages: ["/productDetailImage/printmedien.webp"],
    detailDescription: [
      "Flyer",
      "Visitenkarten",
      "Briefpapier",
      "Briefumschläge",
      "Broschüren",
      "Mappen",
      "Durchschreibsätze",
      "Poster",
      "Plakate",
      "Kataloge",
      "Folder",
      "Aufkleber",
    ],
  },
  {
    id: 3,
    title: "Banner & Planen",
    img: "/productsImage/banner.webp",
    description: "Werbebanner, Mesh-Banner, PVC-Banner",
    path: "/banner-&-planen",
    detailImages: ["/productDetailImage/bannerplanen.webp"],
    detailDescription: [
      "PVC-Planen",
      "Werbeplanen",
      "Gerüstbanner",
      "Bauzaunbanner",
      "Werbeflaggen",
      "Beachflags",
      "Hissflaggen",
      "Roll-Up-Banner",
      "Display-Systeme",
      "Pop-Up-Banner",
    ],
  },
  {
    id: 7,
    title: "Schilder",
    img: "/productsImage/schilder.webp",
    description: "Werbeschilder, Firmenschilder, Leuchtwerbung",
    path: "/schilder",
    detailImages: ["/productDetailImage/schilder.webp"],
    detailDescription: [
      "Firmenschilder",
      "Bauschilder",
      "Werbetafeln",
      "Praxisschilder",
      "Baustellenschilder",
      "Parkplatzschilder",
      "Hinweisschilder",
      "Alu-Dibond-Schilder",
      "Acrylglasschilder",
    ],
  },
  {
    id: 5,
    title: "Fensterwerbung",
    img: "/productsImage/fenster.webp",
    description: "Schaufensterbeschriftung, Glasdekor",
    path: "/fensterwerbung",
    detailImages: ["/productDetailImage/fenster.webp"],
    detailDescription: [
      "Fensterbeschriftung",
      "Fassadenbeschriftung",
      "Dekorfolien",
      "Sichtschutzfolien",
      "Lochfolien (One-Way-Vision)",
      "Sonnenschutzfolien",
      "Werbefolien für Fenster",
    ],
  },
  {
    id: 4,
    title: "KFZ-Werbung",
    img: "/productsImage/kfz.webp",
    description: "Fahrzeugbeschriftung, KFZ-Folierung",
    path: "/kfz-werbung",
    detailImages: ["/productDetailImage/kfz.webp"],
    detailDescription: [
      "Transporter-Beschriftung",
      "PKW-Beschriftung",
      "LKW-Beschriftung",
      "Anhänger-Beschriftung",
      "Teilverklebung",
      "Magnetfolien für Fahrzeuge",
      "Heckscheibenwerbung",
    ],
  },

  {
    id: 6,
    title: "LED-Werbung",
    img: "/productsImage/led.webp",
    description:
      "3D-Buchstaben, Leuchkasten, Neon Schriftzug, LED-Textilspannrahmen",
    path: "/led-werbung",
    detailImages: ["/productDetailImage/led.webp"],
    detailDescription: [
      "3D-Buchstaben",
      "Leuchtkasten",
      "Neon-Schriftzug",
      "LED-Leuchtbuchstaben",
      "Werbepylone mit LED",
      "LED-Lichtleisten",
      "Fassadenleuchten mit LED",
      "LED-Wanddisplays",
    ],
  },

  {
    id: 8,
    title: "Textildruck",
    img: "/productsImage/textilien.webp",
    description: "T-Shirts, Poloshirts, Arbeitsbekleidung",
    path: "/textildruck",
    detailImages: ["/productDetailImage/textildruck.webp"],
    detailDescription: [
      "T-Shirts",
      "Poloshirts",
      "Warnwesten",
      "Hoodies",
      "Jacken",
      "Arbeitskleidung",
      "Caps und Mützen",
      "Stofftaschen",
      "Schürzen",
      "Sportbekleidung",
      "Sweatshirts",
    ],
  },
  {
    id: 9,
    title: "Werbeartikel",
    img: "/productsImage/werbeartikel.webp",
    description: "Kugelschreiber, USB-Sticks, Tassen",
    path: "/werbeartikel",
    detailImages: ["/productDetailImage/webartikel.webp"],
    detailDescription: [
      "Kugelschreiber",
      "Tassen & Gläser",
      "Schlüsselanhänger",
      "Notizblöcke",
      "USB-Sticks",
      "Powerbanks",
      "Tragetaschen",
      "Regenschirme",
      "Kalender",
      "Mousepads",
      "Feuerzeuge",
    ],
  },
  {
    id: 10,
    title: "Messebau",
    img: "/productsImage/messebau.webp",
    description: "Messestände, Roll-Ups, Display-Systeme",
    path: "/messebau",
    detailImages: ["/productDetailImage/messebau.webp"],
    detailDescription: [
      "Roll-Ups",
      "Display-Systeme",
      "LED-Messestand",
      "Messetheken",
      "Messewände",
      "Pop-Up-Displays",
      "Bannerrahmen",
      "Prospektständer",
      "Deckenhänger",
      "Bodenaufkleber",
    ],
  },
];

export default products;
